name: frontend
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.4 <4.0.0'

dependencies:
  http_parser: ^4.0.2
  flutter:
    sdk: flutter
  http: ^1.1.0
  image_picker: ^1.0.4
  shared_preferences: ^2.2.2
  provider: ^6.0.5
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
