name: leafy
description: A plant disease detection app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.3.0
  http_parser: ^4.0.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  jwt_decoder: ^2.0.1
  shared_preferences: ^2.2.2
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  generate: true # Add this line to enable code generation
