# Generated by Django 5.1.2 on 2025-05-08 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_alter_comment_parent_reply_replylike'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='like',
            name='unique_post_like',
        ),
        migrations.RemoveConstraint(
            model_name='like',
            name='unique_comment_like',
        ),
        migrations.RemoveConstraint(
            model_name='like',
            name='like_either_post_or_comment',
        ),
        migrations.AddField(
            model_name='reply',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'comment'), ('user', 'post')},
        ),
    ]
